# This file is autogenerated by the ./cabal2nix script.
# Re-run ./cabal2nix when the dependencies in the cabal
# file have changed.

{ mkDerivation, base, filepath, GLFW, GPipe, GPipe-GLFW
, JuicyPixels, linear, stdenv, transformers
}:
mkDerivation {
  pname = "gpipe-hello";
  version = "0.1.0.0";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  executableHaskellDepends = [
    base filepath GLFW GPipe GPipe-GLFW JuicyPixels linear transformers
  ];
  license = stdenv.lib.licenses.mit;
}
